server:
  port: 8080

spring:
  application:
    name: movies-api
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
      show-sql: true
  datasource:
    url: jdbc:h2:file:./data/movies-api
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
      path: /h2-console

